---
- name: Installs packages
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks: 
  - name: Install telnet
    package:
      name: "{{item}}"
      state: lastest
    with_items:
    - telnet
    - gzip
    - lftp
    - httpd